# Generated by Django 2.1.3 on 2018-12-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='date start')),
                ('exec_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='date exec')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.Status')),
            ],
        ),
    ]
